"""Diagnostic matching engine that evaluates rules against command output."""

from pathlib import Path
from typing import Optional, List, Dict, Any
from bruh.engine.models import DiagnosticResult, SourceLocation, RuleMatch
from bruh.engine.parser import ErrorParser
from bruh.engine.registry import RuleRegistry, get_default_registry
from bruh.personality.phrases import TITLE_UNKNOWN

class DiagnosticEngine:
    """Engine that coordinates parsing, rule matching, and explanation generation."""

    def __init__(self, registry: Optional[RuleRegistry] = None):
        self.registry = registry or get_default_registry()

    def diagnose(
        self,
        raw_output: str,
        command: Optional[str] = None,
        exit_code: Optional[int] = None
    ) -> DiagnosticResult:
        """Analyze raw command output and return a structured DiagnosticResult."""
        cleaned = ErrorParser.clean_output(raw_output)
        location = ErrorParser.extract_location(cleaned)
        ecosystem = ErrorParser.detect_ecosystem(cleaned, command=command)

        if not cleaned:
            return DiagnosticResult(
                is_known=False,
                rule_id="no-output",
                category="general",
                title="Command failed without output",
                original_error="The process exited with a non-zero status but produced no terminal output.",
                location=None,
                explanation="The command exited silently with an error code without printing any error message.",
                suggestions=[
                    "Try running the command with a verbose or debug flag (e.g. `--verbose` or `-v`).",
                    "Check log files generated by the application if available."
                ],
                command=command,
                exit_code=exit_code
            )

        # Iterate through registered rules in priority order
        for rule in self.registry.all_rules():
            match: Optional[RuleMatch] = rule.match(
                cleaned_output=cleaned,
                command=command,
                exit_code=exit_code
            )
            if match and match.matched:
                final_location = match.location or location
                explanation = match.custom_explanation or rule.generate_explanation(match.extracted_vars)
                suggestions = match.custom_suggestions or rule.generate_suggestions(match.extracted_vars)
                title = match.title or rule.name
                original_err = match.original_error or ErrorParser.extract_error_headline(cleaned)

                return DiagnosticResult(
                    is_known=True,
                    rule_id=rule.rule_id,
                    category=rule.category,
                    title=title,
                    original_error=original_err,
                    error_type=match.error_type,
                    error_message=match.error_message,
                    ecosystem=ecosystem,
                    location=final_location,
                    explanation=explanation,
                    suggestions=suggestions,
                    extracted_vars=match.extracted_vars,
                    command=command,
                    exit_code=exit_code
                )

        # UNKNOWN ERROR: Structured, non-hallucinatory, following unified layout contract
        err_type, err_msg = ErrorParser.extract_error_type_and_message(cleaned)
        headline = ErrorParser.extract_error_headline(cleaned)
        error_display = f"{err_type}: {err_msg}" if err_type and err_msg else (err_type if err_type else headline)

        # Build concise 2-sentence explanation with extracted facts
        explanation_parts = ["Bruh couldn't identify the specific cause of this error yet."]
        fact_detail = ""
        if err_type and location and location.line is not None:
            fact_detail = f"But it did find that a {err_type} occurred at line {location.line}."
        elif err_type:
            fact_detail = f"But it did find that a {err_type} was raised."
        elif location and location.line is not None:
            fact_detail = f"Failure occurred on line {location.line} in {Path(location.file).name}."

        if fact_detail:
            explanation_parts.append(fact_detail)

        explanation = "\n\n".join(explanation_parts)

        # Build progressive, contextual suggestions
        suggestions = []
        if location and location.line is not None:
            suggestions.append(f"Check the code around line {location.line}.")
        if location and location.function and location.function != "<module>":
            suggestions.append(f"Look at the function '{location.function}' mentioned in the traceback.")
        suggestions.append("Search for the exact error message in your project or documentation.")

        return DiagnosticResult(
            is_known=False,
            rule_id="unknown",
            category="unknown",
            title=TITLE_UNKNOWN,
            original_error=error_display,
            error_type=err_type,
            error_message=err_msg,
            ecosystem=ecosystem,
            location=location,
            explanation=explanation,
            suggestions=suggestions[:3],
            extracted_vars={},
            command=command,
            exit_code=exit_code
        )
